version: '3.8'

services:
  app:
    build: ./
    command: ./ecom
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5438:5432"
    networks:
      - backend
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./../migrations:/migrations
    networks:
      - backend
    command:
      [ "-path", "/migrations", "-database", "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up" ]
networks:
  backend:
    driver: bridge